# Time-domain pulse synthesis from a harmonic frequency response (Fourier synthesis, not a
# transient solver). `exp(-iωt)` convention, matching the rest of the package.

"""
    time_synthesis(frequencies, spectrum, pulse, times)

Real time-domain signal `p(t) = 2*Re[∫ pulse(f)*spectrum(f)*exp(-i2πft) df]` at each `t` [s]
in `times`, from a one-sided (positive-frequency) complex response `spectrum` sampled at
`frequencies` [Hz] (e.g. a [`FrequencySweep`](@ref)'s `amplitudes`, or a per-frequency
[`received_signal`](@ref)) and a transmit pulse spectrum `pulse(f)`. Trapezoidal quadrature
in frequency, with separate frequency-spacing and finite-bandwidth truncation errors.
`frequencies` must be sorted and strictly positive, since the negative-frequency half of the
spectrum is generated by conjugate symmetry (`spectrum(-f)=conj(spectrum(f))`), not sampled.
The response, phase-reference and gate keywords match the FFT overload below.
"""
function time_synthesis(frequencies::AbstractVector{<:Real},
        spectrum::AbstractVector{<:Number}, pulse, times::AbstractVector{<:Real};
        transmit_response = 1, receive_response = 1, system_response = 1,
        reference_delay::Real = 0.0, gate = nothing)
    weighted = _time_spectrum(frequencies, spectrum, pulse;
        transmit_response, receive_response, system_response, reference_delay)
    all(isfinite, times) || throw(ArgumentError("times must be finite"))
    signal = Float64[2real(sum(weighted[i]*cis(-2pi*frequencies[i]*t)
                     for i in eachindex(weighted))) for t in times]
    return _time_gate!(signal, times, gate)
end

function _time_spectrum(frequencies, spectrum, pulse;
        transmit_response, receive_response, system_response, reference_delay)
    n = length(frequencies)
    n == length(spectrum) ||
        throw(ArgumentError("frequencies and spectrum must have the same length"))
    n >= 2 || throw(ArgumentError("frequencies needs at least two samples"))
    all(f->isfinite(f) && f>0, frequencies) && all(>(0), diff(frequencies)) ||
        throw(ArgumentError("frequencies must be finite, strictly increasing and positive"))
    isfinite(reference_delay) || throw(ArgumentError("reference_delay must be finite"))
    weighted = ComplexF64[pulse(f)*s*cis(-2pi*f*reference_delay)
                          for (f, s) in zip(frequencies, spectrum)]
    for response in (transmit_response, receive_response, system_response)
        weighted .*= _response_values(response, frequencies)
    end
    all(isfinite, weighted) || throw(ArgumentError("spectra and responses must be finite"))
    weighted[1] *= (frequencies[2]-frequencies[1])/2
    for i in 2:(n - 1)
        weighted[i] *= (frequencies[i + 1]-frequencies[i - 1])/2
    end
    weighted[end] *= (frequencies[end]-frequencies[end - 1])/2
    return weighted
end

function _response_values(response, frequencies)
    values = if response isa Number
        fill(ComplexF64(response), length(frequencies))
    elseif response isa AbstractVector
        length(response)==length(frequencies) ||
            throw(ArgumentError("response samples must match frequencies"))
        ComplexF64.(response)
    else
        ComplexF64[response(f) for f in frequencies]
    end
    all(isfinite, values) || throw(ArgumentError("response values must be finite"))
    return values
end

function _time_gate!(signal, times, gate)
    gate === nothing && return signal
    if gate isa Tuple
        length(gate)==2 && all(isfinite, gate) && gate[1]<=gate[2] ||
            throw(ArgumentError("gate must be (start,stop) in seconds, with start <= stop"))
        for i in eachindex(signal, times)
            gate[1]<=times[i]<=gate[2] || (signal[i]=0)
        end
    else
        for i in eachindex(signal, times)
            weight=gate(times[i])
            weight isa Real && isfinite(weight) && 0<=weight<=1 ||
                throw(ArgumentError("gate weights must be finite real values in [0,1]"))
            signal[i] *= weight
        end
    end
    return signal
end

"""
    time_synthesis(frequencies, spectrum, pulse; nfft=nothing, start_time=0,
        transmit_response=1, receive_response=1, system_response=1,
        reference_delay=0, gate=nothing, analytic=false)

FFT synthesis on uniformly spaced positive frequencies [Hz]. Return
`(; times, signal, timestep, period)`, with `period=1/step(frequencies)` [s].
With `analytic=true`, `signal` is the complex positive-frequency representation;
its real part is the default waveform and its magnitude is the envelope. The
complex carrier follows the package's negative-time convention.
Here `period` is the FFT envelope/window length; a non-bin-aligned lowest frequency
also changes the carrier phase between successive windows.
`nfft` controls the number of time samples and must resolve the highest physical
frequency; the default is the next power of two above this Nyquist requirement.
Zero padding refines time sampling, not bandwidth or arrival resolution.
Use the four-positional-argument form for nonuniform frequencies or arbitrary times.

Responses are complex scalar gains, sampled vectors or callables of frequency in
Hz, multiplied once each. The transmit `pulse(f)` is a pressure-amplitude spectrum.
Remove a known propagation delay with `reference_delay` [s], which multiplies the
spectrum by `exp(-2pi*im*f*reference_delay)`. Positive physical path delay otherwise
appears at positive time under the package's `exp(-im*omega*t)` convention.
`gate=(start,stop)` [s] zeros samples outside the inclusive interval; alternatively
pass a callable with real weights in `[0,1]`. Gating does not remove physical paths
from the frequency-domain scattering solution.

Matches the direct trapezoidal synthesis, including half-weighted band endpoints
and an arbitrary lowest frequency. FFTW's negative-sign `fft` implements this
package's harmonic synthesis convention; no conjugation or additional `1/nfft`
normalization is applied. Choose the frequency spacing so the time period exceeds
the delays of interest, and check convergence in bandwidth and frequency spacing.
"""
function time_synthesis(frequencies::AbstractVector{<:Real},
        spectrum::AbstractVector{<:Number}, pulse;
        nfft::Union{Nothing, Integer} = nothing, start_time::Real = 0.0,
        transmit_response = 1, receive_response = 1, system_response = 1,
        reference_delay::Real = 0.0, gate = nothing, analytic::Bool = false)
    weighted=_time_spectrum(frequencies, spectrum, pulse;
        transmit_response, receive_response, system_response, reference_delay)
    df=frequencies[2]-frequencies[1]
    highest_frequency=last(frequencies)
    all(
        delta->isapprox(delta, df; rtol = 1e-10, atol = 32eps(Float64)*highest_frequency),
        diff(frequencies)) ||
        throw(ArgumentError("FFT synthesis requires uniformly spaced frequencies"))
    isfinite(start_time) || throw(ArgumentError("start_time must be finite"))
    minimum_count=max(length(frequencies), floor(Int, 2highest_frequency/df)+1)
    count=nfft===nothing ? nextpow(2, minimum_count) : Int(nfft)
    count>=minimum_count ||
        throw(ArgumentError("nfft must be at least $minimum_count to resolve the highest frequency"))
    timestep=1/(count*df)
    times=collect(range(Float64(start_time); step = timestep, length = count))
    bins=zeros(ComplexF64, count)
    for i in eachindex(weighted)
        bins[i]=weighted[i]*cis(-2pi*frequencies[i]*start_time)
    end
    transformed=FFTW.fft(bins)
    signal=if analytic
        ComplexF64[2transformed[j]*cis(-2pi*first(frequencies)*(j-1)*timestep)
                   for j in 1:count]
    else
        Float64[2real(transformed[j]*cis(-2pi*first(frequencies)*(j-1)*timestep))
                for j in 1:count]
    end
    _time_gate!(signal, times, gate)
    return (; times, signal, timestep, period = 1/df)
end

"""
    tone_burst(frequency, duration; window=:rectangular, phase=0, start_time=0)

Positive-frequency spectrum of a unit-amplitude real cosine burst lasting
`duration` seconds, starting at `start_time` seconds. `frequency` is in Hz and
`phase` in radians. `window=:rectangular` uses an abrupt on/off envelope;
`:hann` tapers both ends to zero over the same duration. Both carrier sidebands
are included in the transform, consistent with `exp(-im*omega*t)` synthesis.
Finite synthesis bandwidth smooths abrupt edges and can cause ringing. Duration
is the full support of the ideal pulse, not a Gaussian FWHM or receiver ring-down.
"""
function tone_burst(frequency::Real, duration::Real;
        window::Symbol = :rectangular, phase::Real = 0.0, start_time::Real = 0.0)
    isfinite(frequency) && frequency>0 ||
        throw(ArgumentError("frequency must be finite and positive"))
    isfinite(duration) && duration>0 ||
        throw(ArgumentError("duration must be finite and positive"))
    isfinite(phase) && isfinite(start_time) ||
        throw(ArgumentError("phase and start_time must be finite"))
    window in (:rectangular, :hann) ||
        throw(ArgumentError("window must be :rectangular or :hann"))
    rectangle=df->duration*cis(pi*df*duration)*sinc(df*duration)
    envelope=window===:rectangular ? rectangle :
             df->rectangle(df)/2-(rectangle(df-1/duration)+rectangle(df+1/duration))/4
    return f->cis(2pi*f*start_time)*(cis(-phase)*envelope(f-frequency)+cis(phase)*envelope(f+frequency))/2
end

"""
    oscillogram(frequencies, responses::NamedTuple, pulse; sound_speed=1500,
        range_origin=0, time_reference=0, kwargs...)

Synthesize named receiver-pressure path spectra coherently. Returns `times`,
`ranges`, real `signal`, magnitude `envelope`, complex `components`,
`component_envelopes`, `timestep` and `period`. Every component must use the same
pressure/gain normalization. Electrical response and FFT keywords pass to
`time_synthesis`; all components receive the same responses and gate.

`ranges = range_origin + sound_speed*(times-time_reference)/2` is a two-way
equivalent range, not exact depth for a bistatic path. For a burst starting at
zero, `time_reference=duration/2` centers its packet at the path's equivalent range;
`range_origin` can account for transducer submergence. Physical sample times remain
referenced to pulse launch. Pulse duration limits uncompressed range separation.
Components are added as complex signals before taking the envelope, so interference
is preserved. This does not add missing propagation paths or synthesize noise/TVG.
"""
function oscillogram(frequencies, responses::NamedTuple, pulse;
        sound_speed::Real = 1500.0, range_origin::Real = 0.0, time_reference::Real = 0.0, kwargs...)
    isempty(responses) && throw(ArgumentError("at least one receiver response is required"))
    isfinite(sound_speed) && sound_speed>0 ||
        throw(ArgumentError("sound_speed must be finite and positive"))
    isfinite(range_origin) && isfinite(time_reference) ||
        throw(ArgumentError("range and time references must be finite"))
    traces=map(
        response->time_synthesis(
            frequencies, response, pulse; analytic = true, kwargs...), responses)
    first_trace=first(traces)
    components=map(trace->trace.signal, traces)
    total=reduce(+, values(components))
    return (; times = first_trace.times,
        ranges = range_origin .+ sound_speed/2 .* (first_trace.times .- time_reference),
        signal = real.(total), envelope = abs.(total), components,
        component_envelopes = map(x->abs.(x), components),
        timestep = first_trace.timestep, period = first_trace.period)
end

function _trapz_complex(x::AbstractVector{<:Real}, y::AbstractVector{<:Complex})
    total = zero(ComplexF64)
    for i in 1:(length(x) - 1)
        total += (x[i + 1] - x[i]) * (y[i] + y[i + 1]) / 2
    end
    return total
end

"""
    gaussian_pulse(f0, bandwidth)

Transmit spectrum of a Gaussian-windowed tone burst at center frequency `f0` [Hz] with
amplitude full width at half maximum `bandwidth` [Hz],
`pulse(f) = exp(-(f-f0)^2/(2σ^2))`,
`σ = bandwidth/(2*sqrt(2*log(2)))`. When `f0` spans many `σ` (negligible spectral weight
reaches `f=0`), its own [`time_synthesis`](@ref) (`spectrum` all ones) approaches the closed
form `2σ*sqrt(2π)*exp(-2π²σ²t²)*cos(2πf0*t)`, used to check the general quadrature.
The half-amplitude points are approximately -6.02 dB; the power -3 dB bandwidth
is `bandwidth/sqrt(2)`. This preserves the original numerical pulse convention.
"""
function gaussian_pulse(f0::Real, bandwidth::Real)
    isfinite(f0) && f0 > 0 || throw(ArgumentError("f0 must be finite and positive"))
    isfinite(bandwidth) && bandwidth > 0 ||
        throw(ArgumentError("bandwidth must be finite and positive"))
    sigma = bandwidth / (2sqrt(2log(2)))
    return f -> exp(-(f - f0)^2 / (2sigma^2))
end
