"""
    RevolvedSurface

A full 3D surface generated by revolving a meridian panel set about the z-axis, `n_phi` steps in
azimuth. `x`/`y`/`z` are `n_phi × npanels` matrices of panel-midpoint positions at each azimuth;
`field` is the complex surface value (`Σₘ modes[m+1][j]·cos(m·phi)`) at the same grid points,
piecewise-constant per panel since this BEM/MFS/shell-FEM discretization has no per-vertex field
data to interpolate against, only per-panel.
"""
struct RevolvedSurface
    x::Matrix{Float64}
    y::Matrix{Float64}
    z::Matrix{Float64}
    field::Matrix{ComplexF64}
end

"""
    revolve_panels(ps::Vector{Panel}, modes::AbstractVector{<:AbstractVector{<:Number}}; n_phi=72)

Revolve meridian panels `ps` about the z-axis into a [`RevolvedSurface`](@ref), evaluating
Fourier-mode surface data `modes[m+1][j]` (panel `j`, mode `m`) at each azimuth via the same
azimuthal expansion used by [`far_field`](@ref). Built from panel midpoints, not endpoints: a
piecewise-constant BEM/MFS/shell-FEM solution has no field value defined at a panel endpoint, so
the midpoint grid is the only representation with an exact, non-interpolated field at every
plotted vertex.
"""
function revolve_panels(ps::Vector{Panel},
        modes::AbstractVector{<:AbstractVector{<:Number}}; n_phi::Integer = 72)
    phis = range(0, 2π; length = n_phi + 1)[1:(end - 1)]
    npanels_ = length(ps)
    m_max = length(modes) - 1
    x = Matrix{Float64}(undef, n_phi, npanels_)
    y = similar(x)
    z = similar(x)
    field = Matrix{ComplexF64}(undef, n_phi, npanels_)
    for (i, phi) in enumerate(phis), (j, p) in enumerate(ps)

        x[i, j] = p.rhom * cos(phi)
        y[i, j] = p.rhom * sin(phi)
        z[i, j] = p.zm
        field[i, j] = sum(modes[m + 1][j] * cos(m * phi) for m in 0:m_max)
    end
    return RevolvedSurface(x, y, z, field)
end
